### ISSUE TITLE
MongoDB dumps for Galaxy Zoo

### ISSUE THREAD

**Issue by willettk** [zooniverse/Galaxy-Zoo#204]
Are the regular data dumps still running? I haven't received one for the past three days for either GZ or RGZ (since June 18).

**Comment by astopy** [comment]
We had an issue with our deployment system that will have affected this. It should be fixed now though, so it'll start working again within the next 24 hours.

**Comment by willettk** [comment]
Should we reopen the issue (or make a new one)? I didn't get a classifications dump on Jun 28, although the daily MongoDB dumps have continued.

**Comment by parrish** [comment]
Yep. It was still broken.  Got it running now, so it should (eventually) be sending you an email with the new data.

**Comment by willettk** [comment]
Just got the emails for both classifications and quiz, thanks.

Is it still possible to get classifications separated by group, like
@parrish did last week?

**Comment by willettk** [comment]
Also, ignore the above; the link to S3 in the email didn't work.

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
ouroboros/2015-06-30_galaxy_zoo_classifications.csv.tar.gz
</Key>
<RequestId>6DB3365B1F2BAF43</RequestId>
<HostId>
2tlfjLzO3VYgHA4PwuRIuCnnFSM0BvQp7ZoRDtUNp73PEKpnmJg7ivz02NDrAsgs
</HostId>
</Error>
```

**Comment by parrish** [comment]
Yep, sorry, the first attempt failed -- hopefully you won't end up with too many more emails for it.
