### ISSUE TITLE
Navigator is not displaying data for new subjects

### ISSUE THREAD

**Issue by willettk** [zooniverse/Galaxy-Zoo#232]
Since adding the DECaLS/Illustris groups to GZ, the Navigator interface doesn't load any of the data for galaxies classified in a group. Both new sets should have all the data properties that it tries to graph, with the possible exception of redshift for Illustris galaxies. 

We encourage lots of classrooms to use Navigator, so it'd be really useful to figure out why it's occurring. 

![screen shot 2015-09-30 at 4 09 12 pm](https://cloud.githubusercontent.com/assets/2285931/10206655/a1ab96f4-678d-11e5-914b-a2ab212b7162.png)

**Comment by edpaget** [comment]
Kyle it looks like https://github.com/zooniverse/Ubret/pull/50 wasn't merged. I've done so now, so the next deploy should fix this.

**Comment by willettk** [comment]
Oh great - thanks, Ed.

Can you do the deploy as well, or should I ask one of the other devs?

**Comment by chrissnyder** [comment]
Deployed the new ubret code and still seeing the same errors. Poked around for a bit, but wasn't able to find what was going on. @edpaget thoughts?

**Comment by chrissnyder** [comment]
Fixed.

**Comment by willettk** [comment]
Thanks, Chris. What was the fix?

**Comment by edpaget** [comment]
We need to compile the code from your Pull Request to Ubret, and you had declared the an array with `()` instead of `[]` which I should have caught.

**Comment by willettk** [comment]
Good to know - thanks, Ed.
